name: Update Azure Boards Ticket Status
description: Update an Azure Boards ticket status
branding:
  icon: columns
  color: blue
inputs:
  pat:
    description: Personal Access Token for Azure Boards
    required: true
  project:
    description: Project name or ID (if you have multiple projects, any would work if you have access to all of them)
    required: true
  ticket-id:
    description: Ticket IDs to update (e.g. "1234" or "AB#1234" or "AB#1234,AB#4321" or "1234,4321")
    required: true
  status:
    description: Status to set the ticket to
    required: true
  status-order-list:
    description: Ordered list of status (in case the ticket needs to be moved to an intermediate status before moving to the final status)
    required: false
    default: New,In Progress,Code Review,Ready for QA,In QA,Ready for regression,Ready for Deploy,Done
  code-review-state:
    description: Name of the code review state
    required: false
    default: Code Review
  allow-back-flow:
    description: Allow changes to previous statuses (e.g. "Code Review" to "In Progress")
    required: false
    default: false
    
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.pat }}
    - ${{ inputs.project }}
    - ${{ inputs.ticket-id}}
    - ${{ inputs.status }}
    - ${{ inputs.status-order-list }}
    - ${{ inputs.code-review-state }}
    - ${{ inputs.allow-back-flow }}